name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: actions/setup-cmake@v1

    - name: Run compile script
      run: |
        chmod +x scripts/compile.sh
        ./scripts/compile.sh -d